// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PLM.Models.EF;

public partial class plmDbContext : DbContext
{
    public plmDbContext(DbContextOptions<plmDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("PK__Roles__2A49584CBFE9E917");

            entity.ToTable("Roles", "seg");

            entity.HasIndex(e => e.Nombre, "UQ__Roles__75E3EFCF43525B55").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(200);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__5B65BF9781CE28A9");

            entity.ToTable("Usuarios", "seg");

            entity.HasIndex(e => e.NombreUsuario, "UQ__Usuarios__6B0F5AE0FCFFAD0A").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D1053416FCA75F").IsUnique();

            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Usuarios__Activo__02FC7413");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Usuarios__FechaC__03F0984C")
                .HasColumnType("datetime");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.UltimoAcceso).HasColumnType("datetime");

            entity.HasMany(d => d.IdRol).WithMany(p => p.IdUsuario)
                .UsingEntity<Dictionary<string, object>>(
                    "UsuarioRoles",
                    r => r.HasOne<Roles>().WithMany()
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK_UsuarioRoles_Rol"),
                    l => l.HasOne<Usuarios>().WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_UsuarioRoles_Usuario"),
                    j =>
                    {
                        j.HasKey("IdUsuario", "IdRol");
                        j.ToTable("UsuarioRoles", "seg");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}