// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PLM.Models.EF;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string NombreCompleto { get; set; }

    public string NombreUsuario { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? UltimoAcceso { get; set; }

    public virtual ICollection<Roles> IdRol { get; set; } = new List<Roles>();
}